version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
###########################################################################


  # postulaciones-service:
  #   build:
  #     context: ./microservices/postulaciones-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - backend-network



# networks:
#   backend-network:

volumes:
  postgres_data:
